import { describe, expect, it } from "vitest";
import { buildReceiptPdfFilename, generateReceiptPdf } from "@/lib/receipts/pdf";
import { ContributionType } from "@/types/enums";
import { ReceiptStatus } from "@/types/receipt";

const sampleReceipt = {
  id: "GIS-20260619-AB1234",
  receiptNumber: "GIS-RCP-20260619-K4FWKR",
  paymentId: "payment-1",
  paymentReference: "GIS-20260619-AB1234",
  contributionId: "contribution-1",
  memberId: "member-1",
  memberName: "Member User",
  serviceNumber: "IS/00002",
  contributionType: ContributionType.MONTHLY_DUES,
  amount: 50,
  currency: "GHS" as const,
  status: ReceiptStatus.ISSUED,
  issuedAt: "2026-06-19T10:00:00.000Z",
  issuedBy: "system",
  createdAt: "2026-06-19T10:00:00.000Z",
};

describe("generateReceiptPdf", () => {
  it("builds a non-empty PDF buffer", async () => {
    const buffer = await generateReceiptPdf(sampleReceipt);

    expect(buffer.byteLength).toBeGreaterThan(0);
    expect(buffer.subarray(0, 4).toString()).toBe("%PDF");
  });

  it("uses an organization-focused receipt layout without developer branding", async () => {
    const buffer = await generateReceiptPdf(sampleReceipt);
    const pdfText = buffer.toString("latin1");

    expect(pdfText).not.toContain("Powered by Brony Hans");
    expect(pdfText).not.toContain("Generated By");
  });

  it("builds a download filename from the receipt number", () => {
    expect(buildReceiptPdfFilename(sampleReceipt)).toBe("GIS-RCP-20260619-K4FWKR.pdf");
  });
});
